sudo: required

language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

install:
  - docker-compose pull

before_script:
  - docker-compose up -d
  - docker-compose ps
  - ls -la

script:
  - docker exec server bin/behat
