sudo: required

language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - composer install

install:
  - docker-compose pull

before_script:
  - docker-compose up -d
  - docker-compose ps

script:
  - docker exec server bin/behat

after_success:
  - "chmod a+x ./travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^\\w*' BRANCH_TO_MERGE_INTO=rc1 GITHUB_REPO=josdagaro/first_bdd_test ./travis-automerge"

branches:
  only:
    - develop