sudo: required

language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose pull
  - docker-compose up -d

script:
  - docker-compose ps
  - ls -la
  - docker exec server bin/behat
