sudo: required

language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose pull
  - docker-compose up -d

script:
  - docker exec server bash -c '/var/www/bin/behat'
