version: '2'

services:
  server:
    build:
      context: ./docker/server/
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ./apache2.conf:/etc/apache2/apache2.conf
    networks:
      - bdd-network
  composer:
    image: composer/composer:latest
    container_name: composer
    volumes:
      - .:/app
    command: install
networks:
  bdd-network:
    driver: bridge
